Use 'TPC/tapyrus' instead 'BTC/satoshi' as the unit
chaintope/rust-tapyrus pull request #29
Opened 2021-02-27 11:09 UTC by Yamaguchi

Change the coin unit as followings:

- BTC -> TPC
- mBTC -> mTPC
- uBTC -> uTPC
- satoshi -> tapyrus
- msat(milli satoshi) -> mtap

2021-02-28 16:06 UTC, Yamaguchi commented
These methods is used esplora-tapyrus(chaintope/esplora-tapyrus#9)

2021-03-01 00:00 UTC, azuchi requested changes
The notation of comments in `src/blockdata/constants.rs` and `src/blockdata/transaction.rs` should also be changed.

2021-03-01 05:40 UTC, Yamaguchi commented
> The notation of comments in `src/blockdata/constants.rs` and `src/blockdata/transaction.rs` should also be changed.

fixed at 41ce580

2021-03-01 05:41 UTC, azuchi approved these changes

2021-03-01 05:41 UTC, merged