Port Schnorr Signature implementation
chaintope/rust-tapyrus pull request #40
Opened 2024-06-06 03:06 UTC by rantan

2024-06-06 07:45 UTC, rantan commented on .github/workflows/rust.yml
> +      - name: Pending
I created an issue to re-enable cross and embedded tests. https://github.com/chaintope/rust-tapyrus/issues/41

2024-06-07 04:47 UTC, Yamaguchi requested changes

2024-06-07 04:47 UTC, Yamaguchi commented on tapyrus/src/crypto/rfc6979.rs
> +        // RVC6979 3.2.h.
```suggestion
        // RFC6979 3.2.h.
```

2024-06-07 04:47 UTC, Yamaguchi commented on tapyrus/src/crypto/schnorr.rs
> +// serde_struct_impl!(Signature, r_x, sigma);
このコードは不要？であればコメントアウトではなく、単純な削除でもよいかと。

2024-06-07 04:49 UTC, Yamaguchi commented
> This PR eliminates changes from the PR under blockdata/ directory because the changes will occur some conflicts while merging future PRs.

blockdata/blocks.rsとblocks/constants.rsの変更は別PRで出すということですか？

2024-06-07 05:04 UTC, rantan commented on tapyrus/src/crypto/rfc6979.rs
> +        // RVC6979 3.2.h.
修正しました。

2024-06-07 05:20 UTC, rantan commented on tapyrus/src/crypto/schnorr.rs
> +// serde_struct_impl!(Signature, r_x, sigma);
削除しました。

2024-06-07 05:55 UTC, merged